
package com.projetandoo.extrator.clienteWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Vendas", 
				  targetNamespace = "http://service.varejodigital.projetandoo/1.0/", 
				  wsdlLocation = "file:/home/fboaretto/Documentos/Projetandoo/WS/21_07/vendas.wsdl")
public class Vendas_Service extends Service
{
    private final static URL VENDAS_WSDL_LOCATION;
    
    private final static WebServiceException VENDAS_EXCEPTION;
    
    private final static QName VENDAS_QNAME = new QName("http://service.varejodigital.projetandoo/1.0/", "Vendas");

    static 
    {
        URL url = null;
        WebServiceException e = null;
        try 
        {
            url = new URL("file:/home/fboaretto/Documentos/Projetandoo/WS/21_07/vendas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENDAS_WSDL_LOCATION = url;
        VENDAS_EXCEPTION = e;
    }

    public Vendas_Service() {
        super(__getWsdlLocation(), VENDAS_QNAME);
    }

    public Vendas_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENDAS_QNAME, features);
    }

    public Vendas_Service(URL wsdlLocation) {
        super(wsdlLocation, VENDAS_QNAME);
    }

    public Vendas_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENDAS_QNAME, features);
    }

    public Vendas_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Vendas_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Vendas
     */
    @WebEndpoint(name = "VendasSOAP")
    public Vendas getVendasSOAP() {
        return super.getPort(new QName("http://service.varejodigital.projetandoo/1.0/", "VendasSOAP"), Vendas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. 
     *     Supported features not in the <code>features</code> 
     *     parameter will have their default values.
     * @return
     *     returns Vendas
     */
    @WebEndpoint(name = "VendasSOAP")
    public Vendas getVendasSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.varejodigital.projetandoo/1.0/", "VendasSOAP"), Vendas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENDAS_EXCEPTION!= null) {
            throw VENDAS_EXCEPTION;
        }
        return VENDAS_WSDL_LOCATION;
    }

}
