
package com.projetandoo.extrator.clienteWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Vendas", targetNamespace = "http://service.varejodigital.projetandoo/1.0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Vendas {

    /**
     * 
     * @param pedido
     * @return
     *     returns src.VendasResponseType
     */
    @WebMethod(action = "salvarVendas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salvarVendas", targetNamespace = "http://service.varejodigital.projetandoo/1.0/", className = "src.SalvarVendas")
    @ResponseWrapper(localName = "salvarVendasResponse", targetNamespace = "http://service.varejodigital.projetandoo/1.0/", className = "src.SalvarVendasResponse")
    @Action(input = "salvarVendas", output = "http://service.varejodigital.projetandoo/1.0/Vendas/salvarVendasResponse")
    public VendasResponseType salvarVendas(
        @WebParam(name = "pedido", targetNamespace = "")
        VendaType pedido);

}
